MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.01

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -8,14 +8,19 @@ osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
+    - CONFIG=osx_python2.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "WiT7VJdBwU6NQoOwRXS22mV3n8VrGupBa/s4/tQAlwN3vzRzuh3m78I5CcwNAQeyuEc0RY4S9lybjYpxMaXnpmKQzY/8KljlmP2AsYDNYIWinrw6SWu6kBsGjLBxq5ALvy/5pwUDuFgC7Be7vki3P3sGR6WwaAD1EblXsJ+JFSiS453qRum88okizZTmgtUMkav0nGUAfCYuIPu0mzYGIANwba1PTy9BofnkyRtOkPIr3dMKJnoGAzVWCDb1GU5YaaKn3h5itY5o+trwaGBrCuSpdYbRJw++iw+q03me0IE+2e7So+l4T1JubLqiXIFrb2foI5/uxgu0WIqD7MYwLZS63UxOqIEk55EjEoKM02PCpWQHxFUzO8c8qZrTMRNm7gy/Irc2t6z6LBgDyblSaWza8tHyu20k0RKVcHfqDaZdF4kxpYdBYyC1gS7YgACT4c3NaTSUfc2elfrLiUbg6MGCgRpvs0cCvDgfQiGI4et0H/TSOr6XB7d5ifrukIKgp+5/3XqvHr/ErTDVKmw81JSJ3KhlzxzPsT8QW/eNwJtKbHcZ43OFu/4/NsYffwjeuSmJKIhuMwKWronziohw/qku2r0Vs+U/huZ+mjWMue2baU5tE/I3+WqGghCsah6Ige+MxBAtFqtV1GqTWzZ5CKcrjKX3gP9Ov5kY2/yN//Y="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
     - |
       echo ""
@@ -41,14 +46,18 @@ install:
       echo ""
       echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --remove channels defaults
-      conda config --add channels defaults
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
